version: "3"

services:
  rabbitmq:
    image: rabbitmq
    expose: 
      - 5672
      - 15672
    networks: 
      - rabbit
  blog:
    build: blog
    depends_on: 
      - rabbitmq
    ports:
      - 3000:80
    volumes: 
      - ./blog:/src
    networks:
      - rabbit
      - mongo
  stats:
    build: stats
    depends_on: 
      - rabbitmq
    volumes: 
      - ./stats:/src
    networks:
      - rabbit
  user:
    build: user
    depends_on: 
      - rabbitmq
    volumes: 
      - ./user:/src
    networks:
      - rabbit
  mongodb:
    image: mongo
    networks:
      - mongo

networks:
  rabbit:
  mongo: